# -*- coding: utf-8 -*-
"""B_2109116074_Posttest1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVTl8RafRtq6Cm5I1weyIwU28rta8Hw4

<h1>Posttest Praktikum Sistem Informasi </h1>

NIM **2109116074**

NAMA **Indra Maulana**

## Visualisasi
"""

import pandas as pd
import seaborn as sns

# Buatlah datasetnya disini
df = pd.read_csv("ChurnBank.csv")

"""### Business Understanding

Sebagai direktur sebuah perusahaan, saya bisa menggunakan dataset churnbank.csv dan algoritma Naive Bayes untuk membantu mengoptimalkan strategi pengambilan keputusan dalam bisnis.

Tujuan penggunaan dataset ini adalah untuk memahami perilaku pelanggan dan melihat pola dari pelanggan yang meninggalkan bisnis (churn). Dataset ini mencakup informasi tentang profil pelanggan, seperti jenis kelamin, usia, status pernikahan, pendapatan, dan apakah mereka memiliki kartu kredit, serta informasi tentang kebiasaan transaksi dan aktivitas rekening.

Tujuan perusahaan adalah untuk meningkatkan retensi pelanggan dan mengurangi tingkat churn. Dengan memahami faktor-faktor yang memengaruhi keputusan pelanggan untuk meninggalkan bisnis, perusahaan dapat mengambil tindakan yang tepat untuk mempertahankan pelanggan dan mengurangi tingkat churn.

Penggunaan algoritma Naive Bayes akan membantu perusahaan dalam memprediksi apakah pelanggan akan churn atau tidak berdasarkan pada data historis dari perilaku pelanggan. Algoritma ini cocok untuk digunakan pada dataset ini karena dataset ini mengandung banyak variabel independen yang dapat memengaruhi tingkat churn. Naive Bayes juga dapat memberikan kemampuan untuk mengidentifikasi variabel mana yang paling penting dalam memprediksi churn sehingga perusahaan dapat mengambil tindakan yang tepat.

### Data Understanding
"""

# df1 isinya dataset dengan label target AttiredCustomer
# df2 dengan label bukan Attrired customer
# df3 dengan tabel untuk usia dibawah 50 tahun
# df4 untuk customer yang statusnya itu single

df_1 = df[df["Attrition_Flag"]=="Attrited Customer"]
df_2 = df[df["Attrition_Flag"]!="Attrited Customer"]
df_3 = df[df["Customer_Age"]<50]
df_4 = df[df["Marital_Status"]=="Single"]

# Tampilkan info dataset (df.info()) dan berikan penjelasannya dalam bentuk teks atau comment
(df.info())

"""Penjelasan:

1. Dataset ini terdiri dari 10 kolom.

2. Kolom-kolom tersebut adalah: Unnamed, CLIENTNUM, Attrition_Flag, Customer_Age, Gender, Education_Level, Marital Status, Income_Category, Card_Category, dan Credit_Limit.

3. Terdapat tiga tipe data yang berbeda dalam dataset ini, yaitu integer (int64), float (float64), dan object.

4. Setiap kolom memiliki 20 nilai non-null, artinya tidak ada nilai yang hilang atau kosong dalam dataset ini.

5. Memori yang digunakan oleh dataset ini adalah sekitar 1.7+ KB.

"""

#@title Opsional (nilai plus)
# Tampilkan nilai rata-rata, min,max, dan standar deviasi  untuk setiap kolom bertipe angka
numeric_cols = df.select_dtypes(include=['int64', 'float64'])
nilai = pd.DataFrame({
    'mean': numeric_cols.mean(),
    'min': numeric_cols.min(),
    'max': numeric_cols.max(),
    'std': numeric_cols.std()
})
# print nilainya
print(nilai)

"""#### Explore Data

##### Visualisasi Comparison
"""

# Attired Customer dan Existing Customer
sns.countplot(data = df,x="Attrition_Flag")

# Education level berdasarkan kategori
sns.countplot(data = df,x="Education_Level")

# Education level berdasarkan gendernya
sns.countplot(x='Education_Level', hue='Gender', data=df)

"""1. Visualisasi Pertama menunjukan Perbandingan pada status atrrition Customer tentang berapa banyak customer yang telah meninggalkan atau berhenti dan yang masih menggunakan produk atau layanan. Dan bisa dilihat pada hasil visualisasi nya menunjukkan banyaknya attrited customer dan existing customer ada pada nilai 10.
2. Visualisasi Kedua Menunjukkan banyaknya Kategori pada level edukasi dan banyaknya customer didalam setiap kategori.
3. Visualisasi Ketiga Menunjukka banyaknya Laki-laki dan perempuan dalam setiap kategori di level edukasi.

##### Visualisasi Distribution
"""

# Historgram untuk umur dan credit card limit
sns.histplot(data=df, x='Customer_Age')

sns.histplot(data=df, x='Credit_Limit')

# Buatlah boxplot untuk umur dan credit card limit
sns.boxplot(data = df,x="Customer_Age")

sns.boxplot(data = df,x="Credit_Limit")

"""1. Visualisasi Histogram pertama menunjukkan berapa banyak customer dalam umur umur tertentu.
2. Visualisasi Histogram Kedua menunjukkan berapa banyak customer dalam Credit Limit tertentu.
3. Visualisasi boxplot Pertama menggambarkan kumpulan data numerik berdasarkan Umur Customer.
4. Visualisasi boxplot Kedua menggambarkan kumpulan data numerik berdasarkan Credit Limit Customer.

##### Visualisasi Relationship
"""

# Buatlah scatterplot untuk umur customer dan credit card limit
sns.scatterplot(data = df,x="Customer_Age",y="Credit_Limit")

"""##### Visualisasi Composition



"""

# Buatlah pieplot untuk Income Category & Education Level
import plotly.express as px
px.pie(df_2,names="Income_Category")

px.pie(df_2,names="Education_Level")

"""### Opsional (Nilai Plus)"""

# Buatlah visualisasi boxplot Credit Card Limit dengan Jenis Kelamin sebagai pemisahnya (color)
sns.boxplot(data=df, x='Gender', y='Credit_Limit')

# Buatlah visualisasi boxplot Credit Card Limit dengan Attrition Flag sebagai pemisahnya (color)
sns.boxplot(data=df, x='Attrition_Flag', y='Credit_Limit')

# Buatlah visualisasi boxplot Age dengan Attrition Flag sebagai pemisahnya (color)
sns.boxplot(data=df, x='Attrition_Flag', y='Customer_Age')

# Buatlah visualisasi countplot  Attrition Flag dengan jenis kelamin sebagai pemisahnya (color)
sns.countplot(x='Attrition_Flag', hue='Gender', data=df)

# Buatlah visualisasi heatmap untuk Setiap variabel numerik yang ada
numeric_cols = df.select_dtypes(include='number')
sns.heatmap(numeric_cols.corr(), annot=True, cmap='coolwarm')

"""## Algoritma Naive Bayes dan Preprocessing (pengenalan)"""

# hapus kolom
dfnb = pd.read_csv("ChurnBank.csv")
dfnb.drop(['Unnamed: 0', 'CLIENTNUM', 'Customer_Age', 'Credit_Limit'], axis=1, inplace=True)
# buat dataframe baru
df_baru = df.copy()
print(df_baru.head())

# Membaca data training
df = pd.read_csv("ChurnBank.csv")

# Hapus data sesuai ketentuan
df = df.drop(["Unnamed: 0", "CLIENTNUM", "Customer_Age", "Credit_Limit"], axis=1)

# memindah data attrition_flag ke ujung kanan
cols = df.columns.tolist()
cols.remove('Attrition_Flag')
cols.append('Attrition_Flag')
df = df[cols]

# Menghitung jumlah data training dan data testing
N_train = len(df)

# Menghitung jumlah kelas target
target_counts = df.groupby('Attrition_Flag')['Attrition_Flag'].count()

# Menghitung probabilitas priori untuk setiap kelas target
prior_prob = target_counts / N_train

# Menghitung probabilitas kondisional untuk setiap fitur pada setiap kelas target
cond_prob = {}
for col in df.columns[:-1]:
    cond_prob[col] = {}
    for val in df[col].unique():
        for target in df['Attrition_Flag'].unique():
            count = len(df[(df[col] == val) & (df['Attrition_Flag'] == target)])
            cond_prob[col][(val, target)] = count / target_counts[target]

# Fungsi Naive Bayes Classifier
def naive_bayes(x):
    prob_yes = prior_prob['Attrited Customer']
    prob_no = prior_prob['Existing Customer']
    for i, col in enumerate(df.columns[:-1]):
        prob_yes *= cond_prob[col][(x[i], 'Attrited Customer')]
        prob_no *= cond_prob[col][(x[i], 'Existing Customer')]
    if prob_no > prob_yes:
        return ('Existing Customer', prob_no)
    else:
        return ('Attrited Customer', prob_yes)

# Contoh penggunaan fungsi naive_bayes
output = naive_bayes(["F","Uneducated","Single","Unknown","Blue"])
print("\nHASIL =", output)